export const Type = {
  ADD_TO_BASKET:'ADD TO BASKET',
   INCREMENT_ITEM: "INCREMENT_ITEM",
   DECREMENT_ITEM: "DECREMENT_ITEM",
   SET_USER:"SET_USER",
   EMPTY_BASKET:"EMPTY_BASKET",
   FAST_BUY:"FAST_BUY"
}